### PR TITLE
feat: site renovation

### PR DESCRIPTION
**Pull request by scoopscode**
- Replaced PPS logo in the middle to PPS777 image from sim
- Made other changes to the site

### CODE REVIEW

**Comment by scoopscode** [comment]
Changing this to a draft after seeing the recent push

**Review by Spherrrical — COMMENTED** [review]
Declined. New tabs are available.

**Comment by scoopscode** [comment]
> Declined. New tabs are available.

That is why I put it on draft cause I'm going to see what other changes I can make. Possibly a redesign.

**Comment by Spherrrical** [comment]
Unable as new pr has new tabs

**Comment by Awemeter** [comment]
Why did you not just rebase?

**Pull request closed without merging**
